Module mdlEnum
    Public Enum CAReport_TableType
        CA_REPORT_TEMP
        CA_REPORT_SUMMARY_TEMP
    End Enum
    Public Enum CAReport_Type
       
        CA_REPORT_DETAILS_BYASSET = 0
        CA_REPORT_DETAILS_BYRATE = 1
        CA_REPORT_DETAILS_BYCATEGORY = 2
        CA_REPORT_SUMMARY_BYRATE = 3
        CA_REPORT_SUMMARY_BYCATEGORY = 4

    End Enum
    Public Enum TaxComPNLEnuItem
        SALES
        OPENSTOCK
        PURCHASE
        DEPRECIATION
        OTHERALLOWEXP
        OTHERNONALLOWEXP
        CLOSESTOCK
        OTHERBUSINC
        DIVIDENDINC
        INTERESTINC
        RENTALINC
        ROYALTYINC
        OTHERINC
        PDFIXASSET
        PDINVEST
        EXEMDIV
        FORINCREMIT
        REALFE
        UNREALFETRADE
        UNREALFENONTRADE
        OTHERNONTAXINC
        INTERESTRESTRICT
        EXPOTHERINTEREST
        EXPLEGAL
        EXPTECHNICAL
        EXPCONTRACTPAY
        EXPDIRECTORFEE
        EXPSALARY
        EXPEMPLOYEESTOCK
        EXPROYALTY
        EXPRENTAL
        EXPREPAIRMAINTENANCE
        EXPRND
        EXPADVERTISEMENT
        EXPTRAVEL
        EXPJKDM
        EXPDEPRECIATION
        EXPDONATIONAPPR
        EXPDONATIONNONAPPR
        EXPZAKAT
        EXPLOSSDISPFA
        EXPENTERTAINNONSTAFF
        EXPENTERTAINSTAFF
        EXPCOMPAUNDPENALTY
        EXPPROVISION
        EXPLEAVEPASSAGE
        EXPFAWRITTENOFF
        EXPUNREALLOSSFE
        EXPREALLOSSFETRADE
        EXPREALLOSSFENONTRADE
        EXPINITIALSUBSCRIPT
        EXPCAPITALEXPENDITURE
        EXPOTHERSEXPENSES
        GROSSPROFIT
        OTHERBALANCINGFIGURE
        TOTALOTHEREXPENSES
        TOTALEXPENSES
        NETPROFITORLOSS
        NONALLOWABLEEXPENSES
        REALFETRADE
        FORECURREXLOSS
    End Enum
End Module
