Module mdlEnum
    Public Enum TaxComPNLEnuItem
        SALES
        OPENSTOCK
        PURCHASE
        DEPRECIATION
        OTHERALLOWEXP
        OTHERNONALLOWEXP
        CLOSESTOCK
        OTHERBUSINC
        DIVIDENDINC
        INTERESTINC
        RENTALINC
        ROYALTYINC
        OTHERINC
        PDFIXASSET
        PDINVEST
        EXEMDIV
        FORINCREMIT
        REALFE
        UNREALFETRADE
        UNREALFENONTRADE
        OTHERNONTAXINC
        INTERESTRESTRICT
        EXPOTHERINTEREST
        EXPLEGAL
        EXPTECHNICAL
        EXPCONTRACTPAY
        EXPDIRECTORFEE          'simkh 2015 su8.1
        EXPSALARY
        EXPEMPLOYEESTOCK
        EXPROYALTY
        EXPRENTAL
        EXPREPAIRMAINTENANCE
        EXPRND
        EXPADVERTISEMENT
        EXPTRAVEL
        EXPJKDM
        EXPDEPRECIATION
        EXPDONATIONAPPR
        EXPDONATIONNONAPPR
        EXPZAKAT
        EXPLOSSDISPFA
        EXPENTERTAINNONSTAFF
        EXPENTERTAINSTAFF
        EXPCOMPAUNDPENALTY
        EXPPROVISION
        EXPLEAVEPASSAGE
        EXPFAWRITTENOFF
        EXPUNREALLOSSFE
        EXPREALLOSSFETRADE    'hogie
        EXPREALLOSSFENONTRADE
        EXPINITIALSUBSCRIPT
        EXPCAPITALEXPENDITURE
        EXPOTHERSEXPENSES

        'LeeCC
        GROSSPROFIT
        OTHERBALANCINGFIGURE
        TOTALOTHEREXPENSES
        TOTALEXPENSES
        NETPROFITORLOSS
        NONALLOWABLEEXPENSES
        'weihong 
        REALFETRADE
        FORECURREXLOSS
    End Enum
End Module
